#!/usr/bin/env python

import sys, os, re

commit_msg_filepath = sys.argv[1]
regex = "^(revert: )?(feat|fix|docs|style|refactor|perf|test|chore|ci)(\(.+\))?: .+"

with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    if not re.search(regex, content):
        print("commit-msg: ERROR! The commit message must follow the format <type>(<optional scope>): <commit message>.\n" \
            + "Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert")
        sys.exit(1)
    if (len(content.partition('\n')[0]) > 100):
        print("commit-msg: ERROR! The commit message must be less than 100 characters")
        sys.exit(1)