#!/usr/bin/env python

# This hook adds a comment to remind users about the commit message format. Do not use this
# if you are also using commitizen as the added comment will end up in your commit message

import sys, os
commit_msg_filepath = sys.argv[1]
with open(commit_msg_filepath, 'r+') as f:
    content = f.read()

    lines = content.split('\n')
    message_template = "{0}\n# Please ensure your commit message is in the format:\n# <type>(<optional scope>): <commit message>\n" \
    	+ "# Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert\n#\n{1}"

    f.seek(0, 0)
    f.write(message_template.format("\n".join(lines[0:4]), "\n".join(lines[4:])))
